### Valid command -> 200
POST http://localhost:3000/query
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDU2ZjlkNDctMzlhNy00ZGU2LWFkYTItZTQ3NjYyYjc5YmYzIiwiaWF0IjoxNjkwMjk0NTM3LCJleHAiOjE2OTM4OTQ1Mzd9.vY6HTQERdId-KtqdSFpu00Uq4xJuO8dLXOtQuE6vxmg

{
  "queryId": "1b7291d4-ac51-46d2-97f1-f5f304100a29",
  "params": []
}

### Valid command -> 200
POST http://localhost:3000/query
Content-Type: application/json

{
  "queryId": "b1e20492-8775-47f3-926d-3729ee2b836d",
  "params": [
    {
      "name": "id_list",
      "value": [1, 10, 20, 30]
    }
  ]
}

### Invalid command because queryId -> 400
POST http://localhost:3000/query
Content-Type: application/json

{
  "queryId": "BLABLA",
  "params": [
    {
      "name": "organizationId",
      "value": 123
    },
    {
      "name": "createdAt",
      "value": "2021-10-29T03:04:00Z"
    }
  ]
}

### Invalid command because params -> 400
POST http://localhost:3000/query
Content-Type: application/json

{
  "queryId": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
  "params": [
    {
      "name": "organizationId",
      "value": null
    },
    {
      "name": "createdAt",
      "valu": "2021-10-29T03:04:00Z"
    }
  ]
}

### Invalid command because query doesn't exist -> 422
POST http://localhost:3000/query
Content-Type: application/json

{
  "queryId": "1b7291d4-ac51-46d2-97f1-f5f304100a20",
  "params": []
}

